#page title
page_title                                : Prism | A versatile music app for Plex & Apple Music.                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1335007451                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Prism Music                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A versatile music app for Plex & Apple Music.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Lachlan Charlick                                
your_link                                 : 
your_city                                 : Adelaide, Australia                                
email_address                             : lachlan@charlick.me
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : lcharlick
github_username                           : lcharlick
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Plex
    description                           : Connect your free Plex account to stream your music from anywhere in the world.
    fontawesome_icon_name                 : chevron-right

  - title                                 : Apple Music
    description                           : Access music on your device or in your iCloud Music Library.
    fontawesome_icon_name                 : mobile

  - title                                 : Filters
    description                           : Refine your library by adding one or more filters.
    fontawesome_icon_name                 : filter

  - title                                 : Arrange
    description                           : Arrange your library using various sorting options. Make any sorting option the default.
    fontawesome_icon_name                 : sort

  - title                                 : CarPlay
    description                           : Access all your music using your car’s built-in controls.
    fontawesome_icon_name                 : car

  - title                                 : Theming
    description                           : Don't like purple? Adjust the app's accent color and app icon to your liking.
    fontawesome_icon_name                 : palette
  


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#292929"
cover_overlay_transparency                : 1.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#151517"

link_color                                : "#8E5AF7"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#BBBBBB"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#8E5AF7"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#292929"

footer_text_color                         : "#BBBBBB"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown